Add step to debug OIDC claims for our Google Auth
Despite our job getting credentials and relaxing our conditions, we're
seeing failures when trying to upload build assets to the Google Play
Console:

```
Error: google-github-actions/auth failed with: failed to generate Google Cloud federated token for //iam.googleapis.com/projects/599269050071/locations/global/workloadIdentityPools/github/providers/whatchord-repo: {"error":"unauthorized_client","error_description":"The given credential is rejected by the attribute condition."}
```

Hopefully this will shed some light on the root cause.